version: '3'
services:
  poweroutagenotifier:
    image: belgradebc/poweroutagenotifier:latest
    container_name: poweroutagenotifier
    volumes:
      - /volume1/docker/poweroutagenotifier:/config
    environment:
      - LOG_CHAT_ID=123456789 # Replace with your actual chat ID
      - enable_reader_on_bot=True
